notifier:
  platforms:
    youtube:
      method: "scraper"
      # optional field, will default to yt-dlp
      # can be set to either 'yt-dlp', 'yt-dlp/piped' or 'ytarchive'
      # downloader: ytarchive
      restream_priority: 1
      google_credentials: client_secret.json
      channel: UCSJ4gkVC6NrvII8umztf0Ow
      refresh_time: 5
      healthcheck: https://hc-ping.com/your-uuid-here
    rumble:
      enabled: yes
      # optional field, will default to yt-dlp
      # can be set to either 'yt-dlp' or 'N_m3u8DL-RE'
      # downloader: N_m3u8DL-RE
      restream_priority: 3
      channel: Destiny
      refresh_time: 5
      healthcheck: https://hc-ping.com/your-uuid-here
    kick:
      enabled: yes
      # optional field, will default to yt-dlp
      # can be set to either 'yt-dlp' or 'N_m3u8DL-RE'
      # downloader: N_m3u8DL-RE
      restream_priority: 2
      channel: destiny
      refresh_time: 5
      healthcheck: https://hc-ping.com/your-uuid-here
  plugins:
    enabled: no
    path: ./notifier.lua
  verbose: no

controller:
  worker_image: ghcr.io/dgghq/dggarchiver-worker:main
  docker:
    enabled: yes
    network: dggarchiver-network
  k8s:
    enabled: no
    namespace: dgghq
    cpu_limit: 150m
    memory_limit: 50Mi
  plugins:
    enabled: no
    path: ./controller.lua
  verbose: no

uploader:
  lbry:
    uri: https://example.com/
    author: example
    channel_name: example
  sqlite: 
    uri: example.sqlite
  plugins:
    enabled: no
    path: ./uploader.lua
  verbose: no

nats:
  host: localhost
  topic: archiver