notifier:
  platforms:
    youtube:
      method: "scraper"
      # optional field, will default to yt-dlp
      # can be set to either 'yt-dlp', 'yt-dlp/piped' or 'ytarchive'
      # downloader: ytarchive
      restream_priority: 1
      google_credentials: client_secret.json
      channel: UCSJ4gkVC6NrvII8umztf0Ow
      refresh_time: 5
      healthcheck: https://hc-ping.com/your-uuid-here
    rumble:
      enabled: yes
      # optional field, will default to yt-dlp
      # can be set to either 'yt-dlp' or 'N_m3u8DL-RE'
      # downloader: N_m3u8DL-RE
      restream_priority: 3
      channel: Destiny
      refresh_time: 5
      healthcheck: https://hc-ping.com/your-uuid-here
    kick:
      enabled: yes
      # optional field, will default to yt-dlp
      # can be set to either 'yt-dlp' or 'N_m3u8DL-RE'
      # downloader: N_m3u8DL-RE
      restream_priority: 2
      channel: destiny
      refresh_time: 5
      healthcheck: https://hc-ping.com/your-uuid-here
  notifications:
    services:
      - example://example:example/
    conditions:
      - example
  verbose: no

controller:
  worker_image: ghcr.io/dgghq/dggarchiver-worker:main
  docker:
    enabled: yes
    network: dggarchiver-network
  k8s:
    enabled: no
    namespace: dgghq
    cpu_limit: 150m
    memory_limit: 50Mi
  notifications:
    services:
      - example://example:example/
    conditions:
      - example
  verbose: no

uploader:
  platforms:
    lbry:
      enabled: yes
      uri: https://example.com/
      author: example
      channel_name: example
    rumble:
      enabled: yes
      login: example
      password: example
    odysee:
      enabled: yes
      email: example@example.com
      password: example
      channel_id: example
  sqlite: 
    uri: example.sqlite
  filters:
    '(?i)example': skip
  notifications:
    services:
      - example://example:example/
    conditions:
      - example
  verbose: no

nats:
  host: localhost
  topic: archiver